<?php

/**
 * @file
 * Contains demosection.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\Entity\User;


/**
 * Implements hook_help().
 */
function demosection_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the demosection module.
    case 'help.page.demosection':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function demosection_theme() {
  return [
    'demosection' => [
      'render element' => 'children',
    ],
  ];
}

function demosection_uninstall() {
    // Delete all of the configuration installed by this module.
    $dir = drupal_get_path('module', 'demosection') . '/config/optional';
    $files = \Drupal::service('file_system')->scanDirectory($dir, '/.*/');
    foreach ($files as $file) {
      \Drupal::configFactory()->getEditable($file->name)->delete();
    }
    \Drupal::logger('demosection')->info(t('Deleted demosection configuration'), []);
}

function demosection_update_9014(){
  // Add Block content first
  $block_content = \Drupal::service('entity_type.manager')->getStorage('block_content')->create([
    'type' => 'basic',
    'info' => 'Demo Block 7',
  ]);
  $block_content->set('body', 'This is demo block for drupal 9');
  $block_content->save();

  // Then Add Block entity to show the bloc and link this to block content
  $blockEntityManager = \Drupal::service('entity_type.manager')->getStorage('block');
  $block = $blockEntityManager->create([
    'id' => 'contrat_block7',
    'plugin' => 'block_content:' . $block_content->uuid(),
    'region' => 'content',
    'provider' => 'block_content',
    'theme' => 'olivero',
    'settings' => [
      'label' => 'Demo Block 7',
      'label_display' => 'visible',
    ],
  ]);
  $block->save();

}

function demosection_form_user_form_alter(&$form, $form_state, $form_id) {
  $form['actions']['submit']['#submit'][] = 'add_user_to_section';
}

function add_user_to_section(&$form, &$form_state){
  $account = User::load($form_state->getValue('uid'));
  if(!$account->get('field_ajout_a_une_section')->isEmpty()){
    $group = $account->get('field_ajout_a_une_section')->first()->get('entity')->getTarget()->getValue();
    $group->addMember($account);
  }
}
